### ISSUE TITLE
Error:no arguments have been passed

### ISSUE THREAD

**Issue by CXXHK** [NullArray/AutoSploit#576]
Hi, why do I report this error after I enter the api interface?

![image](https://user-images.githubusercontent.com/45706420/54551243-a91cfb80-49e8-11e9-81bd-4d8ea5e8efc8.png)

**Comment by Ekultek** [comment]
whats the error?

**Comment by Ekultek** [comment]
looks like it just drops you into the terminal

**Comment by CXXHK** [comment]
> 看起来它只是让你进入终端
![image](https://user-images.githubusercontent.com/45706420/54587556-67796880-4a5b-11e9-9e3a-261e53107dbb.png)
After entering the API, why can't I get this interface?

**Comment by Ekultek** [comment]
The interface has been changed since version 2. We rewrote the entire terminal to be more user friendly and more like an actual terminal. IT is now capable of running not only it's own internal commands but external commands as well. For example if you find an exploit and get something running you can use netcat to bind to it if you so want to.
