### ISSUE TITLE
[Question] Automated Reports

### ISSUE THREAD

**Issue by zero77** [NullArray/AutoSploit#602]
It looks like you are creating automated reports with AutosploitReporter but, without the user having a git account, what are you using to do this.
Thanks

**Comment by Ekultek** [comment]
API tokens. 

 - The token is loaded from [here](https://github.com/NullArray/AutoSploit/blob/master/etc/text_files/auth.key) and is parsed [here](https://github.com/NullArray/AutoSploit/blob/master/lib/creation/issue_creator.py#L35) 
 - From there the issue information is passed to [this](https://github.com/NullArray/AutoSploit/blob/master/lib/creation/issue_creator.py#L113) function by the main function [here](https://github.com/NullArray/AutoSploit/blob/master/autosploit/main.py#L118). 
 - All the stacktraces and error information are pulled from the traceback and formatted correctly and saved to a file (if i remember correctly). 
 - From there the file path is passed to `request_issue_creation` as an argument, it reads a chunk of 4096 bytes and creates an "identifier" out of that, which is basically just the first 10 characters of an SHA-1 hash. 
 - From there it creates a `dict` that will be used as JSON data to be encoded (see [here](https://github.com/NullArray/AutoSploit/blob/master/lib/creation/issue_creator.py#L130)).
 - It then encodes the JSON and ensures that there is not an issue with that same identifier in either the open, or the closed issue links (we still sometimes get duplicates because of paths and operating system data).
 - After that it attempts to create an issue as you can see [here](https://github.com/NullArray/AutoSploit/blob/master/lib/creation/issue_creator.py#L154).
 - If all else fails, it gives you the path to the traceback to create an issue manually as you can see [here](https://github.com/NullArray/AutoSploit/blob/master/lib/creation/issue_creator.py#L174)

It's not a completely foolproof system because there are still duplicates. But it works pretty well and it gives us an idea on how often this program is used, what operating systems are using it, you know just interesting aspects of the program. If you would like, I'm sure we could come up with a way to just completely turn it off if you do not feel comfortable with the idea of your data being thrown around like this?

**Comment by zero77** [comment]
@Ekultek 
Thank you for this detailed response.
> If you would like, I'm sure we could come up with a way to just completely turn it off if you do not feel comfortable with the idea of your data being thrown around like this?


Perhaps enabling it as a debug option or something that needs to be enabled may be a more privacy friendly option.

**Comment by Ekultek** [comment]
The only information that it really gathers is your OS info from `platform.platform()` which in no way can be used to identify you. We also do not keep logs on who has created the issue and use a thirdparty account as the issue creator which neither of us have the password or email address to. Really it's just to help us out as developers to keep updates coming to the tool, we can't update what we don't know is happening. Here's an example of the operating system command ran on both my Linux server and my Mac;

Server: 
```
python -c 'import platform; print platform.platform()'
Linux-4.10.0-27-generic-x86_64-with-Ubuntu-16.04-xenial
```
Mac:
```
python -c 'import platform; print platform.platform()'
Darwin-17.4.0-x86_64-i386-64bit
```

As you can see we really only use it so that we can figure out what OS was being run and test it on there. I can understand your concern about the privacy, but it also prompts you if _you_ would like to create an anonymous issue before it even starts the process. As you can see [here](https://github.com/NullArray/AutoSploit/blob/master/lib/creation/issue_creator.py#L118). If you say anything that starts with the letter `n` it will not create the issue, save the data if you feel like doing it yourself, and exit the program successfully. We as the developers completely respect your privacy.

**Comment by zero77** [comment]
Thanks, i will have a look.
